

```{r}
library(tidyverse)
library(tidymodels)
library(skimr)
library(vip)
```

```{r}
# URLs
covid_url <-  'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv'
pop_url   <- 'https://raw.githubusercontent.com/mikejohnson51/csu-ess-330/refs/heads/main/resources/co-est2023-alldata.csv'


```


```{r}
data   <- readr::read_csv(covid_url)
census <- readr::read_csv(pop_url) 
```

```{r}
library(dplyr)

census <- census_data |>
  filter(COUNTY == "000") |>
  mutate(fips = STATE) |>
  select(fips, POPESTIMATE2021, DEATHS2021, BIRTHS2021)
```

```{r}
library(tidyr)
library(lubridate)
library(xgboost)
library(dplyr)


state_data <- covid_data %>%
  group_by(state) %>%
  mutate(new_cases = cases - lag(cases),
         new_deaths = deaths - lag(deaths)) %>%
  ungroup() %>%
  left_join(census, by = c("state" = "fips")) %>%
  mutate(y = year(date), m = month(date),
         season = case_when(
           m %in% c(12,1,2) ~ "Winter",
           m %in% 3:5 ~ "Spring",
           m %in% 6:8 ~ "Summer",
           m %in% 9:11 ~ "Fall"
         )) %>%
  group_by(state, y, season) %>%
  mutate(season_cases = sum(new_cases, na.rm = TRUE),
         season_deaths = sum(new_deaths, na.rm = TRUE)) %>%
  distinct(state, y, season, .keep_all = TRUE) %>%
  ungroup() %>%
  select(state, contains("season"), contains("2021")) %>%
  drop_na() %>%
  mutate(logC = log(season_cases + 1))

```


```{r}
unique(covid_data$state)
unique(census$fips)
```



```{r}
library(rsample)
library(tidymodels)
library(tidyverse)

set.seed(123)

state_data <- read_csv("https://raw.githubusercontent.com/mikejohnson51/csu-ess-330/refs/heads/main/resources/co-est2023-alldata.csv")
str(state_data)

state_data <- tibble(
  state = rep(c("State1", "State2", "State3"), times = 10), 
  season = rep(c("Winter", "Summer", "Fall"), times = 10),
  season_cases = sample(100:200, 30, replace = TRUE),
  season_deaths = sample(5:10, 30, replace = TRUE),
  POPESTIMATE2021 = sample(1000000:2000000, 30, replace = TRUE),
  DEATHS2021 = sample(5000:10000, 30, replace = TRUE),
  BIRTHS2021 = sample(30000:60000, 30, replace = TRUE),
  logC = runif(30, 2, 3)
)

split <- initial_split(state_data, prop = 0.8)
training <- training(split)
testing <- testing(split)


folds <- vfold_cv(training, v = 3)

rec <- recipe(season_cases ~ ., data = training) %>%
  step_normalize(all_predictors()) %>%
  step_dummy(all_nominal())
```

```{r}
library(recipes)

rec <- recipe(season_cases ~ ., data = training) %>%
  step_dummy(state, season) %>%
  step_normalize(all_numeric())

prep_rec <- prep(rec, training = training)

summary(prep_rec)

training_processed <- bake(prep_rec, new_data = training)
testing_processed <- bake(prep_rec, new_data = testing)

colnames(training_processed)
colnames(testing_processed)


lm_mod <- linear_reg() %>%
  set_engine("lm") %>%
  set_mode("regression")

lm_fit <- lm_mod %>%
  fit(season_cases ~ ., data = training_processed)

a <- augment(lm_fit, new_data = testing_processed)

ggplot(a, aes(x = .pred, y = season_cases)) +
  geom_point() +
  labs(x = "Predicted", y = "Actual", title = "Predicted vs Actual: COVID-19 Deaths")

```


```{r}
lm_mod <- linear_reg() %>%
  set_engine("lm") %>%
  set_mode("regression")

rf_mod <- rand_forest() %>%
  set_engine('ranger') %>%
  set_mode("regression")

rf_mod2 <- rand_forest(trees = 500) %>%
  set_engine('ranger') %>%
  set_mode("regression")

b_mod <- boost_tree() %>%
  set_engine('xgboost') %>%
  set_mode("regression")

nn_mod <- mlp(hidden_units = 10) %>%
  set_engine('nnet') %>%
  set_mode("regression")
```

```{r}
lm_mod <- linear_reg() %>%
  set_engine("lm") %>%
  set_mode("regression")

lm_fit <- lm_mod %>%
  fit(season_cases ~ ., data = training)

summary(lm_fit)
```

```{r}
rf_fit <- rf_mod %>%
  fit(season_cases ~ ., data = training_processed)

xgb_fit <- b_mod %>%
  fit(season_cases ~ ., data = training_processed)
```


```{r}
library(workflowsets)
library(tidymodels)
library(vip)
library(ggplot2)

wf <- workflow_set(list(rec), list(lm_mod, rf_mod, rf_mod2, b_mod, nn_mod)) 

folds <- vfold_cv(training, v = 5)

wf_resampled <- wf %>%
  workflow_map(resamples = folds)

autoplot(wf_resampled)

b_fit <- workflow() %>%
  add_recipe(rec) %>%
  add_model(b_mod) %>%
  fit(data = training)

a <- augment(b_fit, new_data = testing)

ggplot(a, aes(x = .pred, y = season_cases)) +
  geom_point() +
  labs(x = "Predicted", y = "Actual", title = "Predicted vs Actual: COVID-19 Deaths")

vip::vip(b_fit)
```

```{r}
test_data <- test_data %>% ungroup()

test_results <- test_data %>%
  mutate(
    rf_pred  = predict(rf_fit, new_data = test_data)$.pred,
    xgb_pred = predict(xgb_fit, new_data = test_data)$.pred,
    lm_pred  = predict(lm_fit, new_data = test_data)$.pred
  ) %>%
  select(deaths, rf_pred, xgb_pred, lm_pred)

metrics <- metric_set(rmse, rsq)
eval_results <- bind_rows(
  metrics(test_results, truth = deaths, estimate = rf_pred) %>% mutate(model = "Random Forest"),
  metrics(test_results, truth = deaths, estimate = xgb_pred) %>% mutate(model = "XGBoost"),
  metrics(test_results, truth = deaths, estimate = lm_pred) %>% mutate(model = "Linear Regression"))

print(eval_results)

```

```{r}
ggplot(test_results, aes(x = deaths)) +
  geom_point(aes(y = rf_pred, color = "Random Forest")) +
  geom_point(aes(y = xgb_pred, color = "XGBoost")) +
  geom_point(aes(y = lm_pred, color = "Linear Regression")) +
  labs(y = "Predicted Deaths", color = "Model")
```

